"""
RetainIQ — Monitoring & Drift Detection (Phase 3)

Reads the local JSON prediction logs generated by the API
and performs a basic check for data drift by analyzing 
average churn probabilities.

Run:
    python monitor.py
"""

import json
import pandas as pd
from pathlib import Path

LOG_FILE = Path("logs/predictions.log")

def check_drift():
    print("\n📊 Running Basic Drift & Monitoring Check...\n")
    
    if not LOG_FILE.exists():
        print("❌ No prediction logs found. Run some API requests first.")
        return

    # Read JSON lines from the API's prediction log
    records = []
    with open(LOG_FILE, "r") as f:
        for line in f:
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue

    df = pd.DataFrame(records)
    
    if "churn_probability" not in df.columns or "timestamp" not in df.columns:
        print("❌ No churn probabilities or timestamps to analyze in the logs.")
        return

    # Convert timestamps to datetime objects
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    
    # Sort chronologically
    df = df.sort_values(by="timestamp")

    total_preds = len(df)
    avg_prob = df["churn_probability"].mean()
    high_risk_count = len(df[df["prediction"] == "Yes"])
    
    print(f"Total Predictions Processed: {total_preds}")
    print(f"High-Risk Customers Flagged: {high_risk_count}")
    print(f"Overall Average Churn Probability: {avg_prob:.4f}\n")

    import datetime
    # Time-based Drift Comparison: Recent (Last 7 Days) vs Older
    now = pd.Timestamp.utcnow()
    recent_threshold = now - datetime.timedelta(days=7)
    
    recent_df = df[df["timestamp"] >= recent_threshold]
    older_df = df[df["timestamp"] < recent_threshold]

    if not recent_df.empty and not older_df.empty:
        recent_avg = recent_df["churn_probability"].mean()
        older_avg = older_df["churn_probability"].mean()
        diff = recent_avg - older_avg
        
        print("📈 Time-based Drift Comparison:")
        print(f"   Older Average (Before last 7 days): {older_avg:.4f}")
        print(f"   Recent Average (Last 7 days):       {recent_avg:.4f}")
        
        if abs(diff) > 0.05:
            print(f"   ⚠️ DRIFT DETECTED! The average prediction shifted by {diff:+.4f}")
        else:
            print("   ✅ Model behavior looks stable. No significant shift detected.")
    else:
        print("ℹ️ Not enough data points over time to compare 'Recent' vs 'Older' predictions.")
        # Fallback to simple threshold
        if avg_prob > 0.45:
            print("⚠️ WARNING: Overall predicted churn probability is unusually high!")
        else:
            print("✅ Overall probability is within normal limits.")

if __name__ == "__main__":
    check_drift()